name: social_foundation_lc
description: A new Flutter plugin project.
version: 0.1.4
homepage: https://github.com/gohopo/social_foundation_lc
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  social_foundation:
    git:
      url: https://github.com/gohopo/social_foundation.git
    # path: ../../gohopo/social_foundation/
  leancloud_official_plugin:
    git:
      url: https://github.com/gohopo/Realtime-SDK-Flutter.git

flutter:
  plugin:
    platforms:
      android:
        package: com.gohopo.social_foundation_lc
        pluginClass: SocialFoundationLcPlugin
      ios:
        pluginClass: SocialFoundationLcPlugin
