name: social_foundation_lc
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/gohopo/social_foundation_lc
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  social_foundation:
    git:
      url: https://github.com/gohopo/social_foundation.git
  leancloud_official_plugin:
    git:
      url: https://github.com/gohopo/Realtime-SDK-Flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.gohopo.social_foundation_Lc
        pluginClass: SocialFoundationLcPlugin
      ios:
        pluginClass: SocialFoundationLcPlugin
