name: social_foundation_lc
description: A new Flutter plugin project.
version: 0.1.0
homepage: https://github.com/gohopo/social_foundation_lc
publish_to: none

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  social_foundation:
    git:
      url: https://github.com/gohopo/social_foundation.git
    # path: ../../gohopo/social_foundation/
  leancloud_official_plugin:
    git:
      url: https://github.com/gohopo/Realtime-SDK-Flutter.git

dependency_overrides:
  http: 1.2.2
  uuid: 4.5.1
  web: 0.5.1

flutter:
  plugin:
    platforms:
      android:
        package: com.gohopo.social_foundation_lc
        pluginClass: SocialFoundationLcPlugin
      ios:
        pluginClass: SocialFoundationLcPlugin
